Clusterization.Web/Controllers/ClusterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CatalogData;
using Clustering.Web.Models;

namespace Clustering.Web.Controllers
{
    public class ClusterController : Controller
    {
        //
        // GET: /Cluster/5

        public ActionResult Index(int id)
        {
            var model = new ClusterModel() {Id = id};

            using (var dbo = new BiblioEntities())
            {
                model.Title = dbo.CentroidClusters.Where(x => x.Id == id).Select(x => x.Document.Title).First();

                var books = dbo.ClusteredBooks.Where(x => x.ClusterId == id).Select(x => x.Document);
                model.Books = books.Select(book => new DocumentModel
                    {
                        Id = book.Id,
                        Title = book.Title,
                        BBK = book.BBK,
                    }).ToList();
            }

            return View(model);
        }
    }
}

Clusterization.Web/Controllers/DocumentController.cs
using System.Linq;
using System.Web.Mvc;
using CatalogData;
using Clustering.Web.Models;

namespace Clustering.Web.Controllers
{
    public class DocumentController : Controller
    {
        //
        // GET: /Document/

        public ActionResult Index(int id)
        {
            using (var dbo = new BiblioEntities())
            {
                var model = dbo.Documents.Where(x => x.Id == id).Select(book=>new DocumentModel()
                    {
                        Title = book.Title,
                        Id = id,
                        AdditionalTitle = book.AdditionalTitle,
                        Author = book.Author,
                        BBK = book.BBK,
                        City = book.City,
                        DocumentType = book.DocumentType.TypeName,
                        Edition = book.Edition,
                        Editor = book.Editor,
                        Pages = book.Pages,
                        Publish = book.Publish,
                        Serial = book.Serial,
                        Year = book.ImprintYear
                    }).First();
                model.ClusterId = dbo.ClusteredBooks.Where(x => x.Document.Id == id).Select(x => x.ClusterId).First();
                return View(model);
            }
        }
    }
}

Clusterization.Web/Views/Cluster/Index.cshtml
@model Clustering.Web.Models.ClusterModel

@{
    ViewBag.Title = "Бібліотечні описи";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="site-title">
                <h3>@ViewBag.Title</h3>
            </hgroup>
        </div>
    </section>
}
<h2>Розділ №@Model.Id - @Model.Title</h2>
<h4>@Html.ActionLink("Назад","Index","Home",null,null)</h4>
<table>
    <tr>
        <th>№ док.</th>
        <th>Назва</th>
        <th>Індекси ББК</th>
    </tr>

    @foreach (var book in Model.Books)
    {
        <tr>
            <td>@book.Id</td>
            <td>
                @Html.ActionLink(book.Title, "Index", "Document", new { id = book.Id }, null)
            </td>
            <td>
                @book.BBK
            </td>
        </tr>
    }

</table>
<h4>@Html.ActionLink("Назад","Index","Home",null,null)</h4>